### ISSUE TITLE
Cant find  <hdf5.h>

### ISSUE THREAD

**Issue by markh2016** [susilehtola/HelFEM#33]
#include <hdf5.h>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/helfem-common.dir/build.make:244: src/CMakeFiles/helfem-common.dir/general/checkpoint.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:168: src/CMakeFiles/helfem-common.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Before cmake would even work you need to add two lines to the ~/.bashrc  file as follows 

# Cmake variables for CMakeLists.txt for use with fortran and gcc
export CC=/usr/bin/gcc
export FC=/usr/bin/gfortran

#set a  path pointing to the header files 
PATH=$PATH:/usr/include/hdf5/serial/

libhdf5-dev is installed 

returned from issuing  sudo apt install libhdf5-dev

Reading package lists... Done                                                                                
Building dependency tree... Done
Reading state information... Done
libhdf5-dev is already the newest version (1.10.8+repack1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Executing cmake ..  from  subdirectory in HelFEM  directory after git- clone  was fine and reports all found as follows 

-- The CXX compiler identification is GNU 12.2.0
-- The Fortran compiler identification is GNU 12.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP_Fortran: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mark/works/HelFEM/objdir

This built without errors

On issuing make from the build  directory this then reports as above i.e cant find <hd5.h> 

Ran your install script but this fails the same way 

Also reported  were these errors  but nothing serious although  could be corrected 

[ 42%] Building CXX object libhelfem/CMakeFiles/helfem.dir/src/RadialBasis.cpp.o
cd /home/mark/works/HelFEM/objdir/libhelfem && /usr/bin/c++  -I/home/mark/works/HelFEM/libhelfem/include -I/home/mark/works/HelFEM/objdir/libhelfem -g -O2 -Wall -Wno-implicit-fallthrough -Wno-misleading-indentation -DARMA_NO_DEBUG -DARMA_DONT_USE_WRAPPER -fopenmp -O3 -DNDEBUG -std=gnu++11 -MD -MT libhelfem/CMakeFiles/helfem.dir/src/RadialBasis.cpp.o -MF CMakeFiles/helfem.dir/src/RadialBasis.cpp.o.d -o CMakeFiles/helfem.dir/src/RadialBasis.cpp.o -c /home/mark/works/HelFEM/libhelfem/src/RadialBasis.cpp
/home/mark/works/HelFEM/libhelfem/src/RegularizedNucleus.cpp:85:19: warning: ‘double helfem::modelpotential::h_normalization(int)’ defined but not used [-Wunused-function]
   85 |     static double h_normalization(int N) {
      |                   ^~~~~~~~~~~~~~~
/home/mark/works/HelFEM/libhelfem/src/RegularizedNucleus.cpp:28:19: warning: ‘double helfem::modelpotential::normalization_slice(int, std::function<double(double)>&)’ defined but not used [-Wunused-function]
   28 |     static double normalization_slice(int N, std::function<double(double)> & phif) {
      |                   ^~~~~~~~~~~~~~~~~~~

hdf5-dev is installed but not finding the header files for some reason so   I think must be issue with the  MakeLists.txt  file

this  is after installing 
libraries required 

libarmadillo11 libarmadillo-dev libgsl-dev h5utils hdf5-filter-plugin hdf5-plugin-lzf hdf5-tools libhdf5-103-1 libhdf5-cpp-103   libhdf5-cpp-103-1 libhdf5-dev libhdf5-fortran-102  libhdf5-hl-fortran-100 libhdf5-hl-cpp-100 libhdf5-hl-100

os details 
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm

Linux kernel version:  6.1.0-10-amd64

Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Debian 12.2.0-14) 

Thanking you 

Mark

**Comment by susilehtola** [comment]
You need to specify where to find the hdf5 headers. Debian is special and does not put the headers in the usual place.
